name: CMake Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Configure and Build
      run: |
        cmake -B build
        cmake --build build
    - name: Test
      run: exit 1
  
  # test:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: run demo
  #       run: exit 1
    
